### ISSUE TITLE
请问下topicID怎么做的

### ISSUE THREAD

**Issue by hezhongfeng** [calidion/forim#7]
`http://forum.webfullstack.me/topic/56c98798281f156c24da4430`
上面是一个主题的网址，请问topic后面的应该是这个模型的ID吧
请问是怎么做的
我自己是那种1、2、3.。。。。。。。。。
这样的，感觉很蠢。
但是要保证这个iD不重复，是怎么做的呢？
是先生成随机的数，然后去数据库里比对有重复的吗？

**Comment by calidion** [comment]
id是mongodb的id
1,2,3的不是更好嘛？
mongodb生成不了这种ID所以才用这样的ID。

**Comment by hezhongfeng** [comment]
@calidion 
谢谢~
还有个问题，头像您是怎么处理的？
用数据库存储路径？

**Comment by calidion** [comment]
是的。头像未来会采用cloudinary不需要注册，备案即可以使用。
